import Head from "next/head";
import CoinList from "../components/CoinList";
import SearchBar from "../components/SearchBar";

export default function Home({ filteredCoins }) {
  return (
    <div>
      <Head>
        <title>Crypto Coin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchBar />
      <CoinList filteredCoins={filteredCoins} />
    </div>
  );
}

const URL_API =
  "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false";

export const getServerSideProps = async () => {
  const res = await fetch(URL_API);
  const filteredCoins = await res.json();

  return {
    props: {
      filteredCoins,
    },
  };
};
